  name: Build
  on:
    push:
      branches:
        - phase2

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            distribution: 'zulu'
            java-version: '17'

        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2

        - name: Build with Gradle
          run: ./gradlew desktop:dist
